std_msgs/Bool use_auto_clip_point
std_msgs/Bool target
geometry_msgs/Point32 box_size_l
geometry_msgs/Point32 box_tilt_l
geometry_msgs/Point32 clip_point_req_l
geometry_msgs/Point32 box_size_r
geometry_msgs/Point32 box_tilt_r
geometry_msgs/Point32 clip_point_req_r
---
geometry_msgs/Point32 clip_point_l
geometry_msgs/Point32 clip_point_r
# geometry_msgs/Vector3 com
